INSERT INTO
    BOARD(NUM, TITLE, CONTENT, USERID, READCOUNT, CREATEDATE, UPDATEDATE)
VALUES
    (BOARD_SEQ.NEXTVAL, '제목', '내용입니다.', 'SSAR', 0, '2019-04-09', '2019-04-09');


COMMIT;

DELETE FROM board;


SELECT
    *
FROM
    BOARD;